<?php

namespace LaKombi\ResourcesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SrcCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SrcCatRepository extends EntityRepository
{
}
