<?php

namespace LaKombi\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCatRepository extends EntityRepository
{
    public function getCatUser($id)
    {
        return $this->createQueryBuilder('g')
        ->where('g.id' = $id)
        ->addOrderBy('g.id', "DESC")
     }
}
