<?php

namespace LaKombi\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataRepository extends EntityRepository
{
    public function getUserData($id)
    {
        return $this->createQueryBuilder('g')
        ->where('g.id' == $id)
        ->addOrderBy('g.id', "DESC");
     }
}
